#!/bin/bash

export MODEL_PORT=31919
export MODEL_BROADCAST_PORT=31818
export EPICS_CA_SERVER_PORT=34444

echo 'Ports are set up as: '
echo '  MODEL_PORT = ' $MODEL_PORT
echo '  MODEL_BROADCAST_PORT = ' $MODEL_BROADCAST_PORT
echo '  EPICS_CA_SERVER_PORT = ' $EPICS_CA_SERVER_PORT
